version: '3'
services:
  ecsdemo-crystal:
    image: brentley/ecsdemo-crystal
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: ecsdemo-crystal
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecsdemo-crystal
